// Code generated by "stringer -type=ActionStatus"; DO NOT EDIT.

package observer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Running-0]
	_ = x[Iddle-1]
	_ = x[Stopped-2]
}

const _ActionStatus_name = "RunningIddleStopped"

var _ActionStatus_index = [...]uint8{0, 7, 12, 19}

func (i ActionStatus) String() string {
	if i < 0 || i >= ActionStatus(len(_ActionStatus_index)-1) {
		return "ActionStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActionStatus_name[_ActionStatus_index[i]:_ActionStatus_index[i+1]]
}
