// Code generated by "stringer -type=LinuxCommands"; DO NOT EDIT.

package linux

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Mounted-2]
	_ = x[UMounted-4]
	_ = x[CantUmounted-8]
	_ = x[CantMounted-16]
	_ = x[MountedButWrongPlace-32]
	_ = x[NotMounted-64]
	_ = x[AlreadyMounted-128]
	_ = x[UUIDNotExists-256]
	_ = x[CommandError-512]
	_ = x[CommandSuccess-1024]
	_ = x[DiskAvailable-2048]
	_ = x[DiskUnAvailable-4096]
	_ = x[PathCreated-8192]
	_ = x[PathNotExists-16384]
	_ = x[PathExists-32768]
}

const _LinuxCommands_name = "NoneMountedUMountedCantUmountedCantMountedMountedButWrongPlaceNotMountedAlreadyMountedUUIDNotExistsCommandErrorCommandSuccessDiskAvailableDiskUnAvailablePathCreatedPathNotExistsPathExists"

var _LinuxCommands_map = map[LinuxCommands]string{
	0:     _LinuxCommands_name[0:4],
	2:     _LinuxCommands_name[4:11],
	4:     _LinuxCommands_name[11:19],
	8:     _LinuxCommands_name[19:31],
	16:    _LinuxCommands_name[31:42],
	32:    _LinuxCommands_name[42:62],
	64:    _LinuxCommands_name[62:72],
	128:   _LinuxCommands_name[72:86],
	256:   _LinuxCommands_name[86:99],
	512:   _LinuxCommands_name[99:111],
	1024:  _LinuxCommands_name[111:125],
	2048:  _LinuxCommands_name[125:138],
	4096:  _LinuxCommands_name[138:153],
	8192:  _LinuxCommands_name[153:164],
	16384: _LinuxCommands_name[164:177],
	32768: _LinuxCommands_name[177:187],
}

func (i LinuxCommands) String() string {
	if str, ok := _LinuxCommands_map[i]; ok {
		return str
	}
	return "LinuxCommands(" + strconv.FormatInt(int64(i), 10) + ")"
}
