// Code generated by "stringer -type=Linux"; DO NOT EDIT.

package linux

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Mounted-1]
	_ = x[UMounted-2]
	_ = x[MountedButWrongPlace-4]
	_ = x[NotMounted-8]
	_ = x[CommandError-16]
	_ = x[CommandSuccess-32]
	_ = x[PathCreated-64]
	_ = x[PathNotExists-128]
	_ = x[PathExists-256]
}

const (
	_Linux_name_0 = "NoneMountedUMounted"
	_Linux_name_1 = "MountedButWrongPlace"
	_Linux_name_2 = "NotMounted"
	_Linux_name_3 = "CommandError"
	_Linux_name_4 = "CommandSuccess"
	_Linux_name_5 = "PathCreated"
	_Linux_name_6 = "PathNotExists"
	_Linux_name_7 = "PathExists"
)

var (
	_Linux_index_0 = [...]uint8{0, 4, 11, 19}
)

func (i Linux) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _Linux_name_0[_Linux_index_0[i]:_Linux_index_0[i+1]]
	case i == 4:
		return _Linux_name_1
	case i == 8:
		return _Linux_name_2
	case i == 16:
		return _Linux_name_3
	case i == 32:
		return _Linux_name_4
	case i == 64:
		return _Linux_name_5
	case i == 128:
		return _Linux_name_6
	case i == 256:
		return _Linux_name_7
	default:
		return "Linux(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
