// Code generated by "stringer -type=LinuxCommands"; DO NOT EDIT.

package linux

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Mounted-2]
	_ = x[UMounted-4]
	_ = x[MountedButWrongPlace-8]
	_ = x[NotMounted-16]
	_ = x[UUIDNotExists-32]
	_ = x[CommandError-64]
	_ = x[CommandSuccess-128]
	_ = x[PathCreated-256]
	_ = x[PathNotExists-512]
	_ = x[PathExists-1024]
}

const _LinuxCommands_name = "NoneMountedUMountedMountedButWrongPlaceNotMountedUUIDNotExistsCommandErrorCommandSuccessPathCreatedPathNotExistsPathExists"

var _LinuxCommands_map = map[LinuxCommands]string{
	0:    _LinuxCommands_name[0:4],
	2:    _LinuxCommands_name[4:11],
	4:    _LinuxCommands_name[11:19],
	8:    _LinuxCommands_name[19:39],
	16:   _LinuxCommands_name[39:49],
	32:   _LinuxCommands_name[49:62],
	64:   _LinuxCommands_name[62:74],
	128:  _LinuxCommands_name[74:88],
	256:  _LinuxCommands_name[88:99],
	512:  _LinuxCommands_name[99:112],
	1024: _LinuxCommands_name[112:122],
}

func (i LinuxCommands) String() string {
	if str, ok := _LinuxCommands_map[i]; ok {
		return str
	}
	return "LinuxCommands(" + strconv.FormatInt(int64(i), 10) + ")"
}
